CREATE TABLE fund_transfers (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	customer_id BIGINT NOT NULL,
	source_account_id BIGINT NOT NULL,
	beneficiary_id BIGINT NOT NULL,
	destination_account_id BIGINT NULL,
	reference_number VARCHAR(32) NOT NULL,
	transfer_type VARCHAR(20) NOT NULL,
	status VARCHAR(20) NOT NULL,
	currency_code VARCHAR(3) NOT NULL,
	amount DECIMAL(19,2) NOT NULL,
	description VARCHAR(140) NULL,
	beneficiary_name_snapshot VARCHAR(120) NOT NULL,
	destination_bank_snapshot VARCHAR(120) NOT NULL,
	destination_account_masked VARCHAR(34) NOT NULL,
	source_balance_after DECIMAL(19,2) NOT NULL,
	completed_at DATETIME(6) NULL,
	failure_reason VARCHAR(255) NULL,
	created_at DATETIME(6) NOT NULL,
	updated_at DATETIME(6) NOT NULL,
	CONSTRAINT uk_fund_transfers_reference UNIQUE (reference_number),
	CONSTRAINT fk_fund_transfers_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
	CONSTRAINT fk_fund_transfers_source_account FOREIGN KEY (source_account_id) REFERENCES bank_accounts (id),
	CONSTRAINT fk_fund_transfers_beneficiary FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries (id),
	CONSTRAINT fk_fund_transfers_destination_account FOREIGN KEY (destination_account_id) REFERENCES bank_accounts (id),
	CONSTRAINT chk_fund_transfers_amount_positive CHECK (amount > 0.00),
	CONSTRAINT chk_fund_transfers_type CHECK (transfer_type IN ('INTERNAL', 'EXTERNAL')),
	CONSTRAINT chk_fund_transfers_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'REVERSED')),
	INDEX idx_fund_transfers_customer_created (customer_id, created_at),
	INDEX idx_fund_transfers_source_account (source_account_id),
	INDEX idx_fund_transfers_beneficiary (beneficiary_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
