CREATE TABLE payment_cards (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	customer_id BIGINT NOT NULL,
	bank_account_id BIGINT NOT NULL,
	request_number VARCHAR(32) NOT NULL,
	card_type VARCHAR(20) NOT NULL,
	status VARCHAR(30) NOT NULL,
	cardholder_name VARCHAR(100) NOT NULL,
	card_number VARCHAR(19) NULL,
	expiry_date DATE NULL,
	requested_at DATETIME(6) NOT NULL,
	reviewed_by VARCHAR(120) NULL,
	reviewed_at DATETIME(6) NULL,
	review_note VARCHAR(255) NULL,
	activated_at DATETIME(6) NULL,
	blocked_at DATETIME(6) NULL,
	block_reason VARCHAR(255) NULL,
	version BIGINT NOT NULL DEFAULT 0,
	created_at DATETIME(6) NOT NULL,
	updated_at DATETIME(6) NOT NULL,
	CONSTRAINT uk_payment_cards_request_number UNIQUE (request_number),
	CONSTRAINT uk_payment_cards_card_number UNIQUE (card_number),
	CONSTRAINT fk_payment_cards_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
	CONSTRAINT fk_payment_cards_account FOREIGN KEY (bank_account_id) REFERENCES bank_accounts (id),
	CONSTRAINT chk_payment_cards_type CHECK (card_type IN ('DEBIT', 'CREDIT')),
	CONSTRAINT chk_payment_cards_status CHECK (status IN ('PENDING_REVIEW', 'INACTIVE', 'ACTIVE', 'BLOCKED', 'REJECTED', 'EXPIRED')),
	INDEX idx_payment_cards_customer_requested (customer_id, requested_at),
	INDEX idx_payment_cards_status_requested (status, requested_at),
	INDEX idx_payment_cards_account (bank_account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
