CREATE TABLE users (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(30) NOT NULL,
	email VARCHAR(120) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	role VARCHAR(30) NOT NULL,
	enabled BOOLEAN NOT NULL DEFAULT TRUE,
	account_non_locked BOOLEAN NOT NULL DEFAULT TRUE,
	failed_login_attempts INT NOT NULL DEFAULT 0,
	last_login_at DATETIME(6) NULL,
	created_at DATETIME(6) NOT NULL,
	updated_at DATETIME(6) NOT NULL,
	CONSTRAINT uk_users_username UNIQUE (username),
	CONSTRAINT uk_users_email UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE customers (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT NOT NULL,
	customer_number VARCHAR(30) NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	date_of_birth DATE NOT NULL,
	gender VARCHAR(30) NOT NULL,
	identity_type VARCHAR(30) NOT NULL,
	identity_number VARCHAR(80) NOT NULL,
	nationality VARCHAR(100) NULL,
	mobile_number VARCHAR(30) NOT NULL,
	alternative_phone VARCHAR(30) NULL,
	address_line_1 VARCHAR(150) NOT NULL,
	address_line_2 VARCHAR(150) NULL,
	city VARCHAR(100) NOT NULL,
	district VARCHAR(100) NULL,
	province VARCHAR(100) NULL,
	postal_code VARCHAR(20) NULL,
	country VARCHAR(100) NOT NULL,
	profile_image_path VARCHAR(255) NULL,
	status VARCHAR(40) NOT NULL,
	terms_accepted_at DATETIME(6) NULL,
	privacy_accepted_at DATETIME(6) NULL,
	deactivated_at DATETIME(6) NULL,
	created_at DATETIME(6) NOT NULL,
	updated_at DATETIME(6) NOT NULL,
	CONSTRAINT uk_customers_user_id UNIQUE (user_id),
	CONSTRAINT uk_customers_customer_number UNIQUE (customer_number),
	CONSTRAINT uk_customers_identity_number UNIQUE (identity_number),
	CONSTRAINT fk_customers_user_id FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE bank_accounts (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	customer_id BIGINT NOT NULL,
	account_number VARCHAR(30) NOT NULL,
	account_type VARCHAR(30) NOT NULL,
	account_status VARCHAR(40) NOT NULL,
	branch_code VARCHAR(20) NOT NULL,
	currency_code VARCHAR(3) NOT NULL,
	available_balance DECIMAL(19,2) NOT NULL DEFAULT 0.00,
	current_balance DECIMAL(19,2) NOT NULL DEFAULT 0.00,
	opened_at DATETIME(6) NULL,
	frozen_at DATETIME(6) NULL,
	closed_at DATETIME(6) NULL,
	closure_reason VARCHAR(255) NULL,
	created_at DATETIME(6) NOT NULL,
	updated_at DATETIME(6) NOT NULL,
	CONSTRAINT uk_bank_accounts_account_number UNIQUE (account_number),
	CONSTRAINT fk_bank_accounts_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id),
	CONSTRAINT chk_bank_accounts_available_balance_non_negative CHECK (available_balance >= 0.00),
	CONSTRAINT chk_bank_accounts_current_balance_non_negative CHECK (current_balance >= 0.00)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
